apiVersion: v1
kind: Service
metadata:
  name: mickey-service-nginx-p3
spec:
  type: NodePort
  selector:
    app: nginx-p3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30010
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mickey-nginx-deployment-p3
  labels:
    app: nginx-p3
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx-p3
  template:
    metadata:
      labels:
        app: nginx-p3
    spec:
      containers:
      - name: nginx
        image: prmsandhu67/devops-project3:v2
        ports:
        - containerPort: 80
